Задача 1
syoumzic/Robots pull request #1
Opened 2024-02-25 08:19 UTC by syoumzic

Выполнил следующие задачи:
- требуется добавить пункт меню, позвлояющий закрыть приложение
- требуется собрать обработку события выхода из приложения в один метод
и сделать так, чтобы в этом методе выдавался запрос на подтверждение 
выхода (см. класс JOptionPane)
- сделать так, чтобы диалог на основе JOptionPane выдавал текст на кнопках 
на русском языке.

2024-02-28 18:29 UTC, vpyzhyanov commented
![image](https://github.com/syoumzic/Robots/assets/71599019/f5b1f8d9-bc76-4060-a38d-4ddd375c5092)


За форс пуш ещё -1 балл за Git

2024-02-28 18:33 UTC, vpyzhyanov commented
Сборка не прошла

![image](https://github.com/syoumzic/Robots/assets/71599019/333bb066-0a37-48b5-bdbd-9fc2ad9f22e7)

Ничего не скомпилировалось

2024-02-28 18:34 UTC, vpyzhyanov commented
Итоговый jar пустой

![image](https://github.com/syoumzic/Robots/assets/71599019/fb72e61f-91b4-4db4-844f-516a04fd9a0e)

2024-02-28 18:39 UTC, vpyzhyanov commented
Из-за этого проект даже не запускается

2024-02-28 18:51 UTC, vpyzhyanov requested changes
Решение хорошее, но проект даже не запускается((( И как такое оценивать? По идее это 0 баллов.

И доп. задания не сделаны. Явно вы можете лучше. Пока поставлю 6.

2024-02-28 18:51 UTC, vpyzhyanov commented on src/gui/MainApplicationFrame.java
> +        {
зачем эти скобки?

2024-02-28 18:51 UTC, vpyzhyanov commented on src/gui/MainApplicationFrame.java
> - * Следует разделить его на серию более простых методов (или вообще выделить отдельный класс).
От группы extra я ожидаю выполнение таких заданий, а не тупо удалить комментарий с заданием, ничего при этом не поменяв!!! За такие вещи можно вылететь из группы extra

2024-02-29 04:14 UTC, syoumzic commented
как можно было бы изменить тогда структуру проекта без commit -force?

2024-02-29 04:15 UTC, syoumzic commented
maven по итогу должен jar файл создать, разве не только настроить idea?

2024-02-29 14:53 UTC, vpyzhyanov commented
> как можно было бы изменить тогда структуру проекта без commit -force?

Очень просто, обычным коммитом. А если надо слить ветки, то с помощью merge. А вообще структура проекта никакие ограничения на Git не накладывает. Думаю вам надо чуть глубже познакомиться с Git, чтобы лучше его понимать.

2024-02-29 14:56 UTC, vpyzhyanov commented
> maven по итогу должен jar файл создать, разве не только настроить idea?

Не понял что вы имеете в виду, написано не совсем по-русски.

Ещё раз про проблему: Jar пустой, т.к. ничего не скомпилировалось. Настройки IDEA тут ни при чём, она лишь читает то, что в maven прописано (ну или то, что по умолчанию настроено).

2024-03-24 14:18 UTC, merged

2024-03-25 18:35 UTC, vpyzhyanov commented
эмм.... решили на вопросы не отвечать и ничего не исправлять?... ну ладно