Task2
syoumzic/Robots pull request #3
Opened 2024-03-25 18:15 UTC by syoumzic

в методе выхода из приложения теперь сохраняются положения окошек 
(положение на экране, развернутое/свернутое состояние)
при запуске приложения восстанавливается геометрия окошек приложения 
(положение на экране, развернутое/свернутое состояние)

2024-03-25 18:37 UTC, vpyzhyanov commented
Себе для контекста: предыдущая задача прошла без исправления замечаний и ответов на вопросы.

Если в этой будет то же самое, то вы будете исключены из группы extra.

2024-03-25 19:14 UTC, vpyzhyanov requested changes
есть замечания

2024-03-25 19:14 UTC, vpyzhyanov commented on src/main/java/data/Data.java
> +     * Предоставляет итерируемый список
не список, а множество

2024-03-25 19:14 UTC, vpyzhyanov commented on src/main/java/data/Data.java
> + * Класс для хранения абстракных данных
Это не класс, а интерфейс. Не надо людей в заблуждение вводить. Тем более интерфейса "для хранения" быть не может, получается нестыковочка

2024-03-25 19:14 UTC, vpyzhyanov commented on src/main/java/data/DataManager.java
> +public class DataManager implements Data{
А какой смысл создавать интерфейс? Ведь класс ничем не выделяется и ничего не добавляет

Ещё меня очень смущает слово Manager, описание об этом ничего не говорит, а должно бы!

2024-03-25 19:14 UTC, vpyzhyanov commented on src/main/java/data/DataManager.java
> +        storage.put(name, stringBuilder.toString());
вот смотрите к каким усложнениями приводит использование ненужного интерфейса. Тут не сразу можно заметить, что применена рекурсия. Data записывается как одно из полей в Data.

Да и сама это рекурсия создаёт сложность и неочевидность происходящего.

2024-03-25 19:14 UTC, vpyzhyanov commented on src/main/java/data/DataManager.java
> +            Pattern sepRegex = Pattern.compile("(.*?):(.*)");
регулярные выражения - это довольно медленные штуки. Использовать их для такой простой задачи, как десериализиация - неоправданно. Лучше бы в JSON конвертировали какой-нибудь библиотечкой, было бы намного проще

2024-03-25 19:14 UTC, vpyzhyanov commented on src/main/java/data/DataManager.java
> +            if (!sepMatcher.find()) throw new NoSuchElementException();
однострочное программирование - зло. Используйте форматтирование кода

2024-03-25 19:14 UTC, vpyzhyanov commented on src/main/java/data/DataManager.java
> +    public void saveToFile(String path) throws IOException {
вот явное нарушение ООП. Вы назначили файлу ответственность - быть хранилищем данных, но неожиданно для всех, перегрузили его функционалом по чтению и записи в файл

2024-03-25 19:14 UTC, vpyzhyanov commented on src/main/java/data/DataManager.java
> +            while ((line = reader.readLine()) != null) {
рекомендую вам метод `java.nio.file.Files#readAllLines(java.nio.file.Path, java.nio.charset.Charset)`, не мучайтесь больше)

2024-03-25 19:14 UTC, vpyzhyanov commented on src/main/java/data/Savable.java
> + * Интерфейс объектов, которые можно сохранять и воспроизводить
это же не музыкальный трек, чтобы его воспроизводить. Наверное вы имели в виду восстановить?

2024-03-25 19:14 UTC, vpyzhyanov commented on src/main/java/data/Savable.java
> +     * Возвращает себя как объект данных
каких данных? Не понятно. И зачем тоже не понятно

2024-03-25 19:14 UTC, vpyzhyanov commented on src/main/java/data/Savable.java
> +     * Загружает объект по данным
загружает куда? Каким данным?

2024-03-25 19:14 UTC, vpyzhyanov commented on src/main/java/data/Savable.java
> +     * Устанавлеивает объект в значение по умолчанию
какой объект? Что такое "значение по умолчанию" для произвольного объекта?

Как видите интерфейс можно написать гораздо лучше, если добавить туда смысл. Смысл надо брать из того, для чего вы его делаете.

2024-03-25 19:14 UTC, vpyzhyanov commented on src/main/java/data/Savable.java
> +    void setDefault();
не самая удачная идея заставлять разработчиков определять значения по умолчанию в отдельном методе. Для таких значений есть конструктор, это единственно допустимое место для значений по умолчанию.

2024-03-25 19:14 UTC, vpyzhyanov commented on src/main/java/gui/GameWindow.java
> +     * Возвращает себя как объект данных
не надо дублировать описание. Оно наследуется из интерфейса

2024-03-25 19:14 UTC, vpyzhyanov commented on src/main/java/gui/LogWindow.java
> +     * Позволяет сохранять текущий объект
что? Это как сюда попало?

2024-03-25 19:14 UTC, vpyzhyanov commented on src/main/java/gui/LogWindow.java
> +     * Позволяет загружать текущий объект
не надо дублировать

2024-03-25 19:14 UTC, vpyzhyanov commented on src/main/java/gui/LogWindow.java
> +            setIcon(data.getBoolean("isIcon"));
код полностью дублируется другой компонент

2024-03-25 19:14 UTC, vpyzhyanov commented on src/main/java/gui/LogWindow.java
> +        data.setBoolean("isIcon", isIcon);
код полностью дублируется другой компонент

2024-03-25 19:14 UTC, vpyzhyanov commented on src/main/java/gui/MainApplicationFrame.java
> +    private GameWindow gameWindow;
зачем вам эти поля? Они явно лишние. А если их будет 100, то 100 будете создавать?

2024-03-25 19:14 UTC, vpyzhyanov commented on src/main/java/gui/MainApplicationFrame.java
> +                this.getData().saveToFile(System.getProperty("user.home") + "/windowsPreferences.txt");
1. Имя файла должно быть задано в одном месте
2. Лучше это делать в отдельном классе, который будет отвечать за сохранение состояния и за загрузку

2024-03-25 19:14 UTC, vpyzhyanov commented on src/main/java/gui/MainApplicationFrame.java
> +    public Data getData(){
Нарушение ООП: вроде этот класс реализует `Savable`, но при этом он сам не сохраняется и не восстанавливается. Это странно. Это та самая неочевидная рекурсия, которая только путает.

2024-03-25 19:14 UTC, vpyzhyanov commented on src/main/java/gui/RobotsProgram.java
> +            windowsPreferences.loadFromFile(System.getProperty("user.home") + "/windowsPreferences.txt");
дублирование

2024-03-25 19:14 UTC, vpyzhyanov commented on src/main/java/gui/RobotsProgram.java
> +            frame.loadState(windowsPreferences);
Нарушение ответственности. Класс RobotsProgram лезет в ответственность MainApplicationFrame. Все остальные методы находятся там, значит и этот метод тоже должен быть там.

2024-03-25 19:14 UTC, vpyzhyanov commented on src/main/java/gui/RobotsProgram.java
> +            frame.setDefault();
форматирование съехало, отступ нестандартный

2024-03-31 20:07 UTC, vpyzhyanov commented
> Себе для контекста: предыдущая задача прошла без исправления замечаний и ответов на вопросы.
> Если в этой будет то же самое, то вы будете исключены из группы extra.

Почему нет ответов на вопросы?

2024-04-01 08:16 UTC, syoumzic commented on src/main/java/data/DataManager.java
> +public class DataManager implements Data{
Поправил, теперь это объект Data, DataManager теперь новый объект, который управляет состоянием объекта Data (сохраняет в файл и восстанавливае из него)

2024-04-01 08:19 UTC, syoumzic commented on src/main/java/data/DataManager.java
> +        storage.put(name, stringBuilder.toString());
Да в Data может сохранить объект типа Data это позволяет более гибко хранить информацию об объете (реализовано как jsonObject)

2024-04-01 08:20 UTC, syoumzic commented on src/main/java/data/DataManager.java
> +            Pattern sepRegex = Pattern.compile("(.*?):(.*)");
я думал суть самого задания научиться делать это вручную
*изменил: реализовал без регулярных выражений

2024-04-01 08:20 UTC, syoumzic commented on src/main/java/gui/MainApplicationFrame.java
> +                this.getData().saveToFile(System.getProperty("user.home") + "/windowsPreferences.txt");
перенесено в реализацию объекта DataManager

2024-04-01 08:21 UTC, syoumzic commented on src/main/java/gui/MainApplicationFrame.java
> +    public Data getData(){
теперь объект самостоятельно сохраняет себя в объект Data

2024-04-01 08:23 UTC, syoumzic commented on src/main/java/gui/RobotsProgram.java
> +            frame.loadState(windowsPreferences);
перенёс в конструктор MainApplicaitonFrame

2024-04-01 08:23 UTC, syoumzic commented
Поправил

2024-04-01 08:23 UTC, syoumzic commented on src/main/java/data/Data.java
> +     * Предоставляет итерируемый список
исправил

2024-04-01 08:24 UTC, syoumzic commented on src/main/java/data/Data.java
> + * Класс для хранения абстракных данных
интерфейс убрал

2024-04-01 08:24 UTC, syoumzic commented on src/main/java/data/DataManager.java
> +            if (!sepMatcher.find()) throw new NoSuchElementException();
исправил

2024-04-01 10:13 UTC, syoumzic commented on src/main/java/data/DataManager.java
> +    public void saveToFile(String path) throws IOException {
перенёс функционал сохранения на другую сущность

2024-04-01 10:21 UTC, syoumzic commented on src/main/java/data/Savable.java
> +     * Возвращает себя как объект данных
интерфейс позволяет сохранять своё состояние в переменную Data для дальнейшего восстановления из той же переменной Data (в javadoc добавил)

2024-04-01 10:22 UTC, syoumzic commented on src/main/java/data/Savable.java
> +    void setDefault();
перенёс установку значений по умолчанию в конструктор

2024-04-01 10:22 UTC, syoumzic commented on src/main/java/gui/LogWindow.java
> +     * Позволяет сохранять текущий объект
убрал

2024-04-01 10:23 UTC, syoumzic commented on src/main/java/gui/LogWindow.java
> +     * Позволяет загружать текущий объект
убрал

2024-04-01 10:30 UTC, syoumzic commented on src/main/java/gui/LogWindow.java
> +            setIcon(data.getBoolean("isIcon"));
сохранение и восстановление вынесено в отдельный метод loadWindow

2024-04-01 10:30 UTC, syoumzic commented on src/main/java/gui/MainApplicationFrame.java
> +    private GameWindow gameWindow;
убрал

2024-04-01 10:32 UTC, syoumzic commented on src/main/java/gui/RobotsProgram.java
> +            windowsPreferences.loadFromFile(System.getProperty("user.home") + "/windowsPreferences.txt");
исправил

2024-04-01 10:33 UTC, syoumzic commented on src/main/java/gui/RobotsProgram.java
> +            frame.setDefault();
исправил

2024-04-02 12:15 UTC, syoumzic commented on src/main/java/data/Data.java
> +     * Предоставляет итерируемый список
исправил

2024-04-02 12:18 UTC, syoumzic commented on src/main/java/data/DataManager.java
> +            while ((line = reader.readLine()) != null) {
упростил

2024-04-02 12:18 UTC, syoumzic commented on src/main/java/data/Savable.java
> + * Интерфейс объектов, которые можно сохранять и воспроизводить
да, исправил

2024-04-02 12:21 UTC, syoumzic commented on src/main/java/data/Savable.java
> +     * Загружает объект по данным
объявленная функция позволяет восстанавливать своё состояние (javadoc исправил)

2024-04-02 12:22 UTC, syoumzic commented on src/main/java/data/Savable.java
> +     * Устанавлеивает объект в значение по умолчанию
убрал метод setDefault из интерфейса

2024-04-02 12:22 UTC, syoumzic commented on src/main/java/gui/GameWindow.java
> +     * Возвращает себя как объект данных
убрал

2024-04-21 14:26 UTC, vpyzhyanov commented on src/main/java/data/DataManager.java
> +        storage.put(name, stringBuilder.toString());
Ваша цель усложнить код и сделать его более непонятным? Вы переусложнили решение задачи. Если вы думаете, что круто делать сложные структуры там где они не нужны, то это не так

2024-04-21 14:33 UTC, vpyzhyanov commented on src/main/java/utils/Savable.java
> +    void saveState();
А как компонента узнает куда нужно сохранить состояние?

То есть вы хотите навешать на компоненту связи с какими-то объектами, которые ей вообще не нужны? Нехорошо.

2024-04-21 14:33 UTC, vpyzhyanov commented on src/main/java/utils/Savable.java
> +    void loadState() throws NoSuchElementException;
А как компонента узнает откуда нужно восстановить состояние?

То есть вы хотите навешать на компоненту связи с какими-то объектами, которые ей вообще не нужны? Нехорошо.

2024-04-21 14:33 UTC, vpyzhyanov commented on src/main/java/data/Savable.java
> +     * Загружает объект по данным
И что вы сделали?! Я же не спроста задавал такие вопросы:

> загружает куда? Каким данным?

Вообще убрали что загружать и куда загружать. В итоге замечание никак не исправлено

2024-04-21 14:49 UTC, vpyzhyanov requested changes
есть замечания

2024-04-21 14:49 UTC, vpyzhyanov commented on src/main/java/utils/WindowsManager.java
> +    final String path = System.getProperty("user.home") + "/windowsPreferences.txt";
нарушена инкапсуляция!

2024-04-21 14:49 UTC, vpyzhyanov commented on src/main/java/utils/WindowsManager.java
> +    public void saveWindowsPreferences() throws IOException {
этот метод к окнам не имеет никакого отношения (ничего с ними не делает), что он делает в этом классе - непонятно. Как корабль называете, так он и должен плыть.

2024-04-21 14:49 UTC, vpyzhyanov commented on src/main/java/utils/WindowsManager.java
> +        try(PrintWriter writer = new PrintWriter(new FileWriter(path))){
класс перегружен функционалом. Работа с файлами к окнам никакого отношения не имеет. Добро пожаловать на тёмную сторону)

2024-04-21 14:49 UTC, vpyzhyanov commented on src/main/java/utils/WindowsManager.java
> +            if(pointsIndex == -1) throw new IOException();
я уже просил не использовать однострочное программирование

2024-04-22 04:44 UTC, syoumzic commented on src/main/java/utils/WindowsManager.java
> +    public void saveWindowsPreferences() throws IOException {
Перенёс метод в отдельную сущность FileManager (класс для работы с файлом состояния окна)

2024-04-22 04:44 UTC, syoumzic commented
исправил

2024-04-22 19:38 UTC, vpyzhyanov commented on src/main/java/utils/Savable.java
> +    void saveState();
Нет ни ответа, ни исправления!

2024-04-22 19:38 UTC, vpyzhyanov commented on src/main/java/utils/Savable.java
> +    void loadState() throws NoSuchElementException;
Нет ни ответа, ни исправления!

2024-04-22 19:41 UTC, vpyzhyanov commented on src/main/java/data/Savable.java
> +     * Загружает объект по данным
Нет ни ответа, ни исправления!

2024-04-22 19:44 UTC, vpyzhyanov requested changes
Самое важное не исправили(

Как исправите, можете мёрджить

2024-04-22 19:44 UTC, vpyzhyanov commented on src/main/java/utils/FileManager.java
> +                throw new IOException();
всегда прошу писать человекочитаемые сообщения об ошибке

2024-04-23 08:37 UTC, syoumzic commented on src/main/java/data/Savable.java
> +     * Загружает объект по данным
я понял, что нужно. Вынес сохранение отдельно от класса окна.

2024-04-23 08:41 UTC, syoumzic commented on src/main/java/gui/LogWindow.java
> +        data.setBoolean("isIcon", isIcon);
исправил

2024-04-23 08:42 UTC, syoumzic commented on src/main/java/utils/Savable.java
> +    void saveState();
исправил, вынес, теперь окно само себя не сохраняет и не воспроизводит, этим занимаются другие сущности

2024-04-23 08:42 UTC, syoumzic commented on src/main/java/utils/Savable.java
> +    void loadState() throws NoSuchElementException;
исправил

2024-04-23 08:44 UTC, syoumzic commented on src/main/java/utils/WindowsManager.java
> +    final String path = System.getProperty("user.home") + "/windowsPreferences.txt";
исправил

2024-04-23 08:53 UTC, syoumzic commented on src/main/java/utils/FileManager.java
> +                throw new IOException();
исправил

2024-04-23 09:01 UTC, syoumzic commented
исправил

2024-04-29 11:17 UTC, vpyzhyanov approved these changes
можете мёрджить

2024-05-04 14:03 UTC, merged