Task3
syoumzic/Robots pull request #4
Opened 2024-04-09 15:44 UTC by syoumzic

2024-04-16 19:13 UTC, vpyzhyanov requested changes
есть замечания. Задача не выполнена

2024-04-16 19:13 UTC, vpyzhyanov commented on src/main/java/MainApplicationFrame.java
> +public class MainApplicationFrame extends JFrame
если бы вы делали переносом класса через IDEA, то в git этот класс не пометился бы как новый

2024-04-16 19:13 UTC, vpyzhyanov commented on src/main/java/game/GameController.java
> +public class GameController {
Где JavaDoc?

2024-04-16 19:13 UTC, vpyzhyanov commented on src/main/java/game/GameEngine.java
> + * Двиодок для управления роботом
опечатка

2024-04-16 19:13 UTC, vpyzhyanov commented on src/main/java/game/GameEngine.java
> +    GameEngine(PropertyChangeListener gameWindow){
название переменной сбивает с толку. Оно явно не соответствует типу

2024-04-16 19:13 UTC, vpyzhyanov commented on src/main/java/game/GameEngine.java
> +    private PropertyChangeSupport broadcast = new PropertyChangeSupport(this);
очень неудачное название. Не надо применять сетевые термины к классам, которые с ними не имеют ничего общего. Путаете людей только.

2024-04-16 19:13 UTC, vpyzhyanov commented on src/main/java/game/GameEngine.java
> +    public double angleNormalize(double angle){
инкапсуляция вышла погулять и не вернулась(

2024-04-16 19:13 UTC, vpyzhyanov commented on src/main/java/game/GameEngine.java
> +    public int round(double value) {
а тут вы прям очередью прошлись по всей парадигме ООП. Всё нарушили. 

Этот метод явно должен быть не здесь. Он используется только в одном единственном классе, притом не в этом.

2024-04-16 19:13 UTC, vpyzhyanov commented on src/main/java/game/GameVisualizer.java
> + * Движок для отображения робота
Движок? В каком месте? Давайте лучше общаться в терминах MVC

2024-04-16 19:13 UTC, vpyzhyanov commented on src/main/java/game/GameEngine.java
> +public class GameEngine {
Лучше бы вы использовали термины MVC, было бы намного лучше для всех

2024-04-16 19:13 UTC, vpyzhyanov commented on src/main/java/game/GameVisualizer.java
> +                engine.setTargetPosition(e.getPoint());
по хорошему представление не должно менять модель напрямую

2024-04-16 19:13 UTC, vpyzhyanov commented on src/main/java/game/GameVisualizer.java
> +public class GameVisualizer extends JPanel{
что-то я не наблюдаю прослушивания событий изменения модели.... странно....

2024-04-16 19:13 UTC, vpyzhyanov commented on src/main/java/game/GameController.java
> +                visualizer.onRedrawEvent();
Вот оно что..... оказывается задача не выполнена. Читайте внимательнее условие задачи.

> - модель нужно будет описать как обозреваемый объект (Observable),
чтобы затем окно могло подписаться на уведомления от модели и
обновлять свое состояние

2024-04-16 19:13 UTC, vpyzhyanov commented on src/main/java/game/GameWindow.java
> +public class GameWindow extends JInternalFrame
используйте перемещение классов. Этот код ведь не новый

2024-04-16 19:13 UTC, vpyzhyanov commented on src/main/java/game/RobotPositionWindow.java
> +    void updateContent(double x, double y){
что-то с инкапсуляцией вы отказываетесь дружить. Этот метод не должен вызывать никто, кроме самого класса.

2024-04-16 19:13 UTC, vpyzhyanov commented on src/main/java/game/RobotPositionWindow.java
> +//        textArea.setText("Координаты робота:\nx: %f\ny: %f".formatted(engine.getRobotPositionX(), engine.getRobotPositionY()));
для кого комментарий?

2024-04-16 19:13 UTC, vpyzhyanov commented on src/main/java/game/RobotPositionWindow.java
> +        double[] position = (double[])evt.getNewValue();
зачем? Модели вам недостаточно? Она содержит исчерпывающую информацию

2024-04-16 19:13 UTC, vpyzhyanov commented on src/main/java/gui/MainApplicationFrame.java
очень плохо, что удалили

2024-04-16 19:13 UTC, vpyzhyanov commented on src/main/java/gui/GameVisualizer.java
очень плохо, что удалили

2024-04-16 19:13 UTC, vpyzhyanov commented on src/main/java/gui/GameWindow.java
очень плохо, что удалили

2024-04-16 19:13 UTC, vpyzhyanov commented on src/main/java/log/LogWindow.java
вот здесь же получилось перенести

2024-04-16 19:13 UTC, vpyzhyanov commented on src/main/java/log/LogWindow.java
> +package log;
не согласен. Почему вдруг это теперь не GUI? Это по прежнему окно. Если хотите его всё-таки унести в отдельный пакет (зачем-то), то унесите в gui.log

2024-04-16 19:13 UTC, vpyzhyanov commented on src/main/java/menu/ActionMenu.java
> +public class ActionMenu extends JMenu {
Где JavaDoc?

2024-04-16 19:13 UTC, vpyzhyanov commented on src/main/java/menu/CustomMenuBar.java
> +public class CustomMenuBar extends JMenuBar {
Где JavaDoc?

2024-04-16 19:13 UTC, vpyzhyanov commented on src/main/java/menu/LookAndFeelMenu.java
> +public class LookAndFeelMenu extends JMenu {
Где JavaDoc?

2024-04-16 19:13 UTC, vpyzhyanov commented on src/main/java/menu/TestMenu.java
> +public class TestMenu extends JMenu {
Где JavaDoc?

2024-04-20 07:07 UTC, syoumzic commented on src/main/java/menu/TestMenu.java
> +public class TestMenu extends JMenu {
добавил

2024-04-20 07:07 UTC, syoumzic commented on src/main/java/menu/LookAndFeelMenu.java
> +public class LookAndFeelMenu extends JMenu {
добавил

2024-04-20 07:07 UTC, syoumzic commented on src/main/java/menu/CustomMenuBar.java
> +public class CustomMenuBar extends JMenuBar {
добавил

2024-04-20 07:07 UTC, syoumzic commented on src/main/java/menu/ActionMenu.java
> +public class ActionMenu extends JMenu {
добавил

2024-04-20 07:07 UTC, syoumzic commented on src/main/java/log/LogWindow.java
> +package log;
переместил logWindow в пакет gui, как и все остальные окна

2024-04-20 07:07 UTC, syoumzic commented on src/main/java/game/RobotPositionWindow.java
> +        double[] position = (double[])evt.getNewValue();
убрал evt.getSource()

2024-04-20 07:07 UTC, syoumzic commented on src/main/java/game/RobotPositionWindow.java
> +//        textArea.setText("Координаты робота:\nx: %f\ny: %f".formatted(engine.getRobotPositionX(), engine.getRobotPositionY()));
убрал

2024-04-20 07:07 UTC, syoumzic commented on src/main/java/game/RobotPositionWindow.java
> +    void updateContent(double x, double y){
изменил на private

2024-04-20 07:07 UTC, syoumzic commented on src/main/java/game/GameController.java
> +                visualizer.onRedrawEvent();
а разве не новое окно с координатами должно быть прослушивающим?

2024-04-20 07:08 UTC, syoumzic commented on src/main/java/game/GameVisualizer.java
> +public class GameVisualizer extends JPanel{
прослушивание происходит в новом окне с координатами (RobotPositionWindow)

2024-04-20 07:08 UTC, syoumzic commented on src/main/java/game/GameVisualizer.java
> +                engine.setTargetPosition(e.getPoint());
Переместил в gameController

2024-04-20 07:08 UTC, syoumzic commented on src/main/java/game/GameEngine.java
> +public class GameEngine {
переименовал класс на GameModel

2024-04-20 07:08 UTC, syoumzic commented on src/main/java/game/GameVisualizer.java
> + * Движок для отображения робота
поменял на: "Представление робота"

2024-04-20 07:08 UTC, syoumzic commented on src/main/java/game/GameEngine.java
> +    public int round(double value) {
переместил метод в класс gameVisualizer

2024-04-20 07:08 UTC, syoumzic commented on src/main/java/game/GameEngine.java
> +    public double angleNormalize(double angle){
изменил модификатор доступа на private

2024-04-20 07:08 UTC, syoumzic commented on src/main/java/game/GameEngine.java
> +    private PropertyChangeSupport broadcast = new PropertyChangeSupport(this);
изменил на support

2024-04-20 07:08 UTC, syoumzic commented on src/main/java/game/GameEngine.java
> +    GameEngine(PropertyChangeListener gameWindow){
изменил название на listener

2024-04-20 07:08 UTC, syoumzic commented on src/main/java/game/GameEngine.java
> + * Двиодок для управления роботом
исправил

2024-04-20 07:08 UTC, syoumzic commented on src/main/java/game/GameController.java
> +public class GameController {
добавил

2024-04-21 14:57 UTC, vpyzhyanov commented on src/main/java/game/GameVisualizer.java
> +public class GameVisualizer extends JPanel{
Вы не поняли, оно **должно быть здесь тоже**!!!! Оно должно быть везде, где отрисовывается модель!

2024-04-21 15:01 UTC, vpyzhyanov commented on src/main/java/game/GameController.java
> +                visualizer.onRedrawEvent();
Не исправлено!

Представьте, что ваша программа сохраняла состояние в файл. В следующей задаче вы добавили ещё окно и поменяли место хранения на базу данных. Приходите показывать задачу, а у вас новое окно сохраняется в базу данных, а старые в файл. Нормально? Очевидно что нет. Дак вот тут то же самое. Меняете архитектуру, дак меняйте её везде.

2024-04-21 15:06 UTC, vpyzhyanov commented on src/main/java/game/RobotPositionWindow.java
> +        double[] position = (double[])evt.getNewValue();
Не исправлено!

Вы совсем не читаете замечание или просто не вникаете? Тут же написано, что надо использовать модель, при этом вы удаляете модель.

Не надо лишней информации передавать. Она дублируется в данном случае.

2024-04-21 15:08 UTC, vpyzhyanov requested changes
есть замечания

2024-04-21 15:08 UTC, vpyzhyanov commented on src/main/java/gui/RobotPositionWindow.java
>          double[] position = (double[])evt.getNewValue();
Используйте модель

2024-04-22 06:48 UTC, syoumzic commented on src/main/java/game/GameController.java
> +                visualizer.onRedrawEvent();
исправил, теперь gameVisualizer также реализует модель observer

2024-04-22 06:48 UTC, syoumzic commented on src/main/java/game/RobotPositionWindow.java
> +        double[] position = (double[])evt.getNewValue();
исправил, теперь использую модель и извлекаю из неё значения

2024-04-22 06:49 UTC, syoumzic commented
исправил

2024-04-22 19:53 UTC, vpyzhyanov requested changes
После того как смёрджите 2 задачу и исправите оставшиеся замечания по этой задаче, можете мёрджить эту тоже.

2024-04-22 19:53 UTC, vpyzhyanov commented on src/main/java/game/GameVisualizer.java
> +    private double robotPositionX = 0;
Зачем вы убрали модель и сделали копию координат? Теперь у вас одни и те же данные дублируются. Возвращайте как было, было намного лучше.

2024-04-22 19:53 UTC, vpyzhyanov commented on src/main/java/game/GameVisualizer.java
> +           robotPositionX = model.getRobotPositionX();
Нет дублированию данных!

2024-04-29 11:25 UTC, vpyzhyanov approved these changes
Можете мёрджить

2024-05-04 14:10 UTC, merged